create table dealers
(
  id         int auto_increment
    primary key,
  am         varchar(500) null,
  trade_name varchar(500) null,
  firm_name  varchar(500) null,
  location   varchar(500) null,
  district   varchar(500) null,
  state      varchar(500) null,
  dp_name    varchar(500) null,
  phone      double       null,
  email      varchar(500) null,
  address    varchar(500) null
);

INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (1, 'Saubhagya', 'Sakambari EeVe', 'Sakambari Automobiles Pvt. Ltd.', 'Cuttack', 'Cuttack', 'Odisha', 'Mr. Rahul Kumar Gupta', 8895714483, 'sakambariautomobiles@gmail.com', 'Plot no-2147, Payton Sahi, Haripur Road, Cuttack, Odisha-753001');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (2, 'Vijay', 'Urmila EeVe', 'Urmila Agency', 'Ranchi', 'Ranchi', 'Jharkhand', 'Mrs. Urmila Devi', 9771169401, 'urmilaagency.rnc@gmail.com', 'At-Saparom, Ps-Nagri, Ranchi, Ranchi, Jharkhand - 835303');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (3, 'Saubhagya', 'Chetna EeVe', 'Chetna Tractors And Earthmovers', 'Angul', 'Angul', 'Odisha', 'Mrs. Laxmi Agarwalla', 9438575982, 'chetnatractorearthmovers399@gmail.com', 'House No:AHS (II) 015, Left to Mirania Tower, Gandhimarg, Distt. Angul, Odisha - 759122');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (4, 'Shuvojit', 'Raj & Rajanya EeVe', 'Raj & Rajanya EeVe', 'Barobisha', 'Alipurduar', 'West Bengal', 'Mr. Badal Das', 8167887800, 'badaldasbarobisha@gmail.com', 'NH-31C, Near Indian Oil Petrol Pump, Barobisha, Alipurduar, West Bengal - 736207 ');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (5, 'Soumya', 'Tara EeVe', 'Tara EeVe', 'Bagnan', 'Howrah', 'West Bengal', 'Mr. Sandip Garai', 9330106119, 'p_garai@yahoo.co.in', 'O.T Road, Jeet Honda Building, Bagnan, Howrah, West Bengal - 711303');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (6, 'Monjit', 'Shree EeVe', 'Shree E - Bikes', 'Nagaon', 'Nagaon', 'Assam', 'Mr. Vinod Kumar Verma', 9864888886, 'ashish123.85@gmail.com', 'Laukhowa Road, Near Pani Tanky, Haibargaon, Nagaon, Assam - 782002');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (7, 'Saubhagya', 'J K EeVe', 'J K Automobiles', 'Dhenkanal', 'Dhenkanal', 'Odisha', 'Mr. Jyoti Ranjan Gochhayat', 9439004222, 'jyotirinku222@gmail.com', 'Near Sasan Chowk, Towards Angul Road, Opposite Evening Post Office, Dhenkanal, Odisha - 759001');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (8, 'Saubhagya', 'Anjali EeVe', 'Anjali Enterprises', 'Bhubaneswar', 'Khordha', 'Odisha', 'Mr. Abhishek Pani', 9861303737, 'abhishek.pani93@gmail.com', 'D-2/2, Rasulgarh Industrial Estate, Rasulgarh, Bhubaneswar, Khordha, Odisha - 751010');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (9, 'Saubhagya', 'Exclusive EeVe', 'Exclusive EeVe', 'Puri', 'Puri', 'Odisha', 'Mr. Bibudha Ranjan Mohapatra', 8763300643, 'adlibpuri@gmail.com', 'Near Amala Club, College Road, Puri, Odisha - 752001');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (10, 'Abraham', 'KVR EeVe', 'KVR Motors', 'Srikakulam', 'Srikakulam', 'Andhra Pradesh', 'Mr. Kovvuri Veera Raghava Reddy', 9908815444, 'raghavareddy9999@gmail.com', 'Sri Venkata Laxmi Nivas, Pedapadu Road, Near Harika In Kalyanmadapam, Srikakulam, Andhra Pradesh - 532001');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (11, 'Abraham', 'Annapoorna EeVe', 'Annapoorna Motors', 'Vizianagaram', 'Vizianagaram', 'Andhra Pradesh', 'Mr. A. Venu Gopal', 9246553455, 'venugopalarisetty@gmail.com', 'S/o. Venkatarao, Kothagraharam, 1st Lane, 4-2-27A, Vizianagaram, Andhra Pradesh - 535001');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (12, 'Soumya', 'Navya EeVe', 'Navya Automobiles', 'Behala (Kolkata)', 'South 24 Parganas', 'West Bengal', 'Mrs. Anjana Guha', 9874408700, 'anandinternational482@gmail.com', '233, Diamond Harbour Road, Behala, Pathakpara, Kolkata, South 24 Parganas, West Bengal - 700034');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (13, 'Suman', 'Subham EeVe', 'Subham Auto', 'Durgapur', 'West Burdwan', 'West Bengal', 'Mr. Subham Mukherjee', 9734446666, 'mukherjeesubham925@gmail.com', 'Sanjib Sarani, Santiban Park, Jharna Complex, Durgapur-1, West Burdwan, West Bengal - 713201');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (14, 'Abraham', 'VB EeVe', 'VB Motors', 'Vishakhapatnam', 'Vishakhapatnam', 'Andhra Pradesh', 'Mr. Ramachandra Reddy', 9492101555, 'kvreddy6699@gmail.com', '45-56-1/5/1, GSP Complex, 2nd Floor, Flat No:301, Near Port Hospital, Narasimha Nagar Highway, Akkayyapalem, Vishakhapatnam, Andhra Pradesh - 530024');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (15, 'Abraham', 'Varahi EeVe', 'Varahi Motors', 'Rajahmundry', 'East Godavari', 'Andhra Pradesh', 'Mr. Karri Srinivasa Reddy', 7901495555, 'ramachandra.reddy@live.com', 'Anaparthi Mandal, Koppavaram Village, Rajahmundry, East Godavari, Andhra Pradesh - 533005');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (16, 'Pinaki', 'Bike EeVe', 'Bike Bazar', 'Kharagpur', 'Paschim Medinipur', 'West Bengal', 'Mr. Dipsankar Konar', 9647273247, 'dipsankarkonar1993@gmail.com', 'Inda, Vidyasagarpur, Near Jharia Substation, Kharagpur, Paschim Medinipur, West Bengal - 721301');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (17, 'Saubhagya', 'B & K EeVe', 'B & K Enterprises', 'Sambalpur', 'Sambalpur', 'Odisha', 'Mr. Kishore Agrawal', 9861764200, 'bkenterprisesburla@gmail.com', 'C/o- Panda Cycle Store, Shop No-9, G.B. Market, Burla, Sambalpur, Odisha - 768017');
INSERT INTO eeve.dealers (id, am, trade_name, firm_name, location, district, state, dp_name, phone, email, address) VALUES (52, 'Monjit', 'Wings EeVe', 'Wings EeVe', 'Jorhat', 'Jorhat', 'Assam', 'Mr. Devorup Baruah', 6001848871, 'bdevorup@gmail.com', 'Jail Road, Jorhat, Assam - 785001');